apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: default
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: default
    url: http://loki:3100
    baseicAuth: false
    isDefault: false
    editable: true